---
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - '**/*'
      except:
        changes:
          - .github/workflows/*

variables:
  DOCKER_IMAGE: "service-factory"
  DOCKER_TAG: "latest"
  IMAGE_DISTRIBUTOR: "cloudputation"
  DOCKER_REGISTRY: "registry.gitlab.com"
  NOMAD_HOST: "10.100.200.241"

build-binary:
  script:
    - make build
  artifacts:
    paths:
      - ./build/

build-docker-image:
  needs:
    - job: build-binary
  script:
    - make docker-build
  artifacts:
    paths:
      - ./build/

push-docker-image:
  needs:
    - job: build-docker-image
  script:
    - make docker-push

deploy-service:
  needs:
    - job: push-docker-image
  script:
    - terraform -chdir=$(pwd)/infra/terraform init
    - terraform -chdir=$(pwd)/infra/terraform apply -auto-approve -var nomad_server_address="http://${NOMAD_HOST}:4646" -var jobspec_path="$(pwd)/infra/nomad/jobspec.nomad"
