---
workflow:
  rules:
    - changes:
        - "main.go"
        - "packages/*.go"
        - "Dockerfile"
        - ".gitlab-ci.yml"
        - ".release/docker/docker-entrypoint.sh"
        - ".github/workflows/build-and-release.yml"

variables:
  DOCKER_IMAGE: "service-factory"
  DOCKER_TAG: "latest"
  IMAGE_DISTRIBUTOR: "cloudputation"
  DOCKER_REGISTRY: "registry.gitlab.com"
  NOMAD_HOST: "10.100.200.241"
  GITHUB_SF_TOKEN: "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"
  GITHUB_REMOTE_URL: "https://${GITHUB_SF_TOKEN}@github.com/cloudputation/service-factory.git"

build-binary:
  script:
    - make build
  artifacts:
    paths:
      - ./build/

build-docker-image:
  needs:
    - job: build-binary
  script:
    - sudo make docker-build
  artifacts:
    paths:
      - ./build/

push-docker-image:
  needs:
    - job: build-docker-image
  script:
    - sudo make docker-push DOCKER_REGISTRY=$DOCKER_REGISTRY

deploy-service:
  needs:
    - job: push-docker-image
  script:
    - terraform -chdir=$(pwd)/infra/terraform init
    - terraform -chdir=$(pwd)/infra/terraform apply -auto-approve -var nomad_server_address="http://${NOMAD_HOST}:4646" -var jobspec_path="$(pwd)/infra/nomad/jobspec.nomad"

set-repo-for-github-release:
  needs:
    - job: deploy-service
  script:
    - rm -rf GIT_CONTROLS/
    - rm -rf helpers/
    - rm -rf infra/
    - rm -rf tests/
    - rm -f .on-save.json
    - rm -f .gitlab-ci.yml
    - rm -rf .git
    - rm -f .gitignore
    - touch itworks
    - echo "it works!" > itworks

    # Initialize a new git repository
    - git init
    - git config --global user.name 'GitHub Actions'
    - git config --global user.email 'actions@github.com'

    # Add new remote
    - git remote add origin $GITHUB_REMOTE_URL

    # Create and switch to the 'main' branch
    - git checkout -b main

    # Add, commit, and push changes
    - git add .
    - git commit -m "Release commit"
    - git push -u origin main --force
  only:
    - main
