name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.21'

    - name: Read API_VERSION
      run: echo "VERSION=$(cat API_VERSION)" >> $GITHUB_ENV

    - name: Build Binary
      run: make build

    - name: Build Docker Image
      run: make docker-build

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: $DOCKER_REGISTRY
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker Image
      run: |
        make docker-push DOCKER_REGISTRY=$DOCKER_REGISTRY
