name: Build and Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**'  # Ignore all paths by default
    paths:
      - '!.github/workflows/**'  # Run only if changes in the workflows directory
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'  # Prevent running if commit made by GitHub Actions

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Remove Unnecessary Files and Directories
      run: |
        rm -rf GIT_CONTROLS/
        rm -rf helpers/
        rm -rf infra/
        rm -rf tests/
        rm -f .on-save.json
        rm -f .gitlab-ci.yml
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -A
        git commit -m "Remove unnecessary files [skip ci]"
        git push

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -A
        git commit -m "Remove unnecessary files and directories [skip ci]" || true  # The 'true' ensures the workflow doesn't fail if there's nothing to commit
        git push

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - name: Read API_VERSION
      id: read_version
      run: echo "VERSION=$(cat API_VERSION)" >> $GITHUB_ENV

    - name: Build using Makefile
      run: make build

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ env.VERSION }}"
        release_name: "Release v${{ env.VERSION }}"
        draft: false
        prerelease: false
        body: "Service Factory binary release"
        files: |
          build/service-factory
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean build directory
      run: make clean
